# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags:
      - "*"

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run lint
          npm run build
  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: delete_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: test
          suppress_errors: true
      # Get the output from the `delete_release` step
      - name: Get the output delete_release
        run: echo "The deleted_assets was ${{ steps.delete_release.outputs.deleted_assets }}"
